### ISSUE TITLE
IE Excavator mines Limonite etc. blocks

### ISSUE THREAD

**Issue by Serikuser** [oitsjustjose/Geolosys#117]
## Versions:

- Minecraft Forge: 14.23.4.2703
- Geolosys: 1.9.1
- JourneyMap (optional):
- ImmersiveEngineering (optional): 0.12 - 82

## What happens:

IE Excavator mines Limonite, etc. blocks and its cant be crushed in to dust or ore with any crushers (IE,Thermal, IC, etc...) so you need to mine it with hand tool.

**Comment by oitsjustjose** [comment]
This is intended and I'm not changing it - IE is not optimized for mining up *items* (clusters).

Sorry for the inconvenience, I just figured if IE and Geolosys were installed, some form of breaker is also installed.

**Comment by duncanwebb** [comment]
Would it be possible to ore dict the geolosys raw ores so they are treated like the vanilla equivalent. For example oreBlockHematite -> oreIron. Not sure how you could to the same for Limonite as this results in oreIron and oreNickel.

Unfortunately there is no block breaker in https://minecraft.curseforge.com/projects/real-tech as the pack developer only want multi-block machines and the crusher or magneticraft's grinder don't know haw to process geolosys block ores.

Great mod, I'm really enjoying playing with it and thank you for all the time you have invested in developing it.

**Comment by duncanwebb** [comment]
This might help https://github.com/BluSunrize/ImmersiveEngineering/issues/3372

**Comment by oitsjustjose** [comment]
I suppose I could add those natively into geolosys :)

**Comment by oitsjustjose** [comment]
So there - this not only adds all of Geolosys's ore blocks to the crusher's crushing abilities, but also makes it so that it still drops what it should (including compatibility drops).

There are a few bonuses for doing it this way too (since it's so much effort):

- Galena Ore Block will crush into both Silver and Lead clusters with 100% chance of getting both
- Teallite and Azurite (richer forms of Cassiterite and Malachite respectively) have a chance of dropping a second cluster
- Autunite and Platinum will drop Yellorium and Osmium (respectively and if enabled) alongside their primary drop with a 100% chance
- Limonite will drop nickel with a 40% chance instead of the default 20%
- Assorted Quartz, Cinnabar, Lapis and Coal can drop random multiples (chance based)

**Comment by duncanwebb** [comment]
Thank you very much it works a treat.
