### ISSUE TITLE
Fortune Compatability

### ISSUE THREAD

**Issue by renadi** [oitsjustjose/Geolosys#140]
## Versions:  

- Minecraft Forge:  14.23.4.2705
- Geolosys:              1.9.4
- JourneyMap (optional):
- ImmersiveEngineering (optional):

## What happens:
Ores only drop one output, in vanilla it has to be this way because you get the ore block which would obviously cause issues.

## What could happen:
An optional config in the ore line to say whether it is affected by fortune or not, that would allow you to set your own metals and ores to be fortunable.

**Comment by oitsjustjose** [comment]
This doesn't really fit in with the scheme of the mod.

There are a huge variety of ways (with other mods) to gain the extra resources you'd obtain by fortune (be it crusher, pulverizer, smeltery, etc), and if you don't have one of those then you probably don't need the extra ores considering the average size of a mineral deposit.

**Comment by Teascade** [comment]
I'm currently using a modpack with a friend that we've modified to our own likings, and getting iron is very rare and the veins are somewhat small to what we need. A configuration like this would be really handy, since we only have Immersive Engineering, in which ore duplication is a pretty endgame stuff.

**Comment by oitsjustjose** [comment]
Sure, why not.
