### ISSUE TITLE
Json file error

### ISSUE THREAD

**Issue by Davoleo** [oitsjustjose/Geolosys#153]
## Versions:

- Minecraft Forge: 2750
- Geolosys: 2.1.0
- JourneyMap (optional): 5.5.2
- ImmersiveEngineering (optional): 0.12-82

## What happens:
Default Clusters do not generate in a newly created world

## What should happen:
Clusters should generate in the world

## Logs (if necessary):
https://gist.github.com/Davoleo/ab6ae51739623f9bceb198099f53ea1d

## Additional Comments:
The json files resets to 0 everything, so I assume I made a mistake editing it, if yes what's this mistake? I really can't find it :P 
Json file: https://gist.github.com/Davoleo/ab6ae51739623f9bceb198099f53ea1d

It also would be really nice if instead of resetting everything to 0 
the mod would not load the file and you would get an error in chat with sort of a stacktrace
however that is just a suggestion...

sorry for bad english, I'm italian

**Comment by oitsjustjose** [comment]
This is the ***old*** formatting of the `geolosys_ores.json` file. It changed a little while ago, actually. The new format looks like [this](https://pastebin.com/Ye3A51N9).

The old formatting is not compatible, but don't worry - I've upgraded yours to the new format [here](https://pastebin.com/3PR1jBzc) :smile:

As for your recommendation for not loading the file - I think it would be better to leave it as it is; it only sets things to 0 that aren't there, this is because usually someone deletes it thinking "I don't want ANY" which breaks my code. JSON isn't nearly as easy to use in Java as Python unfortunately.

**Comment by Davoleo** [comment]
oki, thanks very much for updating it to the new format!
it was still using the old one because I used another's modpack file as a model to edit.

And about the json file reset I can understand since I've experienced how complicated is using JSON in Java, it's ok as it is 👍

**Comment by darthvader45** [comment]
Found out about the new format, and just edited my ores json file.  Just making sure it doesn't reset, unless the format changed again.

Edit: Okay, it worked, now everything's generated and I can find deposits now.  This minor setback I had will not stop me from completing my zombie apocalypse base and fulfilling the challenge I made inspired by steelfeathers' Castle Building Challenge.
