### ISSUE TITLE
Suggestion: Make it possible to restrict ores to certain types of biomes

### ISSUE THREAD

**Issue by Rimevel** [oitsjustjose/Geolosys#168]
Would it be possible to add an optional element to the config for each ore, restricting spawning to only happen in biomes with one or more specified biome types? Or even make certain biome types increase or decrease the spawn chance?

It would make setting up camp in multiple locations, transporting goods as well as trading in MP more fun and interesting.

**Comment by Pentasis** [comment]
I was about to make the same request.I did see however it was made in the past and rejected #36 
The suggestion in that issue of using Cofh world is something I am currently doing but the problems I am facing with that are:
a) No surface samples
b) Cluster-sizes are very small compared to geolosys (there seems to be a size restriction in cofh)
So hopefully oitsjustjose will reconsider?

**Comment by oitsjustjose** [comment]
The girlfriend (a geologist) and I have been talking about doing this for almost 7 months, I just haven’t had the time and nor has she. She was going to help me out by providing a list of what ores generate where. They’d be hard-codes and custom entries would require them to be specified. 

I might look into it for Version 3 *a long time from now*, but currently I’m spending all my time studying, working or trying to find side work to make poverty less miserable. Haven’t had much time for modding. 

Closing for now because I know I won’t forget to do this. It’s active on our minds.

**Comment by copygirl** [comment]
Could this be revisited? Right now, you can specify in which specific biomes certain ores can generate using their resource location, such as `minecraft:desert` or `biomesoplenty:outback`. With big biome mods, finding their type, such as whether they're desert-like, can be quite a pain.

Therefore it would be nice if we could also specify where they may generate based on the [biome dictionary type](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L48-L94), instead.

Possibly even a set of types, such as: `(SANDY & HOT & DRY) | SAVANNA`

**Comment by oitsjustjose** [comment]
Ah yes, working on that now. I'm glad you brought it up, I had forgotten about it completely!

**Comment by oitsjustjose** [comment]
@copygirl Doing the compound BiomeTypes structure like you had mentioned would be pretty difficult (just to parse and convert to logic, really) - but I've added BiomeType support in general - and that by itself took a lot of reworking!

**Comment by copygirl** [comment]
That was quick!
