### ISSUE TITLE
Invalid blockstate property format

### ISSUE THREAD

**Issue by LokyLive** [oitsjustjose/Geolosys#208]
## Versions:

- Minecraft Forge: 1.12.2
- Geolosys: 3.0.4
- Contenttweaker:4.9.1
- Crafttweaker: 4.1.19

## What happens:
I'm trying to add ore to worldgen using the crafttweaker support, and i don't found the good syntax to specify meta  
It just said "WARNING: Invalid blockstate property format '2'.Using default property value 

script: 
https://paste.dimdev.org/mahozoyugu.cpp

Could you give me some help or tell me what i'm doing wrong please ?

**Comment by oitsjustjose** [comment]
See [the docs](http://geolosys.oitsjustjose.com/en/latest/CraftTweaker/) for what is meant by `blockstate` -- `blockstate` almost never includes metadata unless a dev has designed it that way - for example, the `blockstate` for a Limonite ore block is `variant=limonite` even though its metadata is *technically* `1`. 

Modders are switching to this because in 1.13+ Minecraft is flattening out Items and Blocks - i.e. metadata won't exist -- all you have is separate `blocks`, `blockstates`, and `NBT` at your disposal.

**Comment by LokyLive** [comment]
i've found an other way . Thanks for your time and your kindness

**Comment by copygirl** [comment]
@LokyLive: For future people finding this issue, please document your solution.

**Comment by LokyLive** [comment]
i've just used the JSON file ,p
