### ISSUE TITLE
Density config seems broken

### ISSUE THREAD

**Issue by barttraeger** [oitsjustjose/Geolosys#220]
# Versions
MC 1.12.2
Forge Version:
14.23.5.2847
Mod Version:
Geolosys 1.12.2 3.0.8
# Other Mods
none

Hi, really love your mod, great work!
I was tweaking the config to get a more scattered ore generation instead of one solid mass,
but the "density" config seems quite broken.
To see an actual effect you have to set the density extremely low, like 0.01.
This seems to kinda work sometimes, but most of the time the generator gets funky on the edges of the deposit and generates it solid anyways.
Here are some screenshots and my config values:
![2019-11-08_14 15 20](https://user-images.githubusercontent.com/57531292/68479577-ed3c6500-0232-11ea-8366-5c662aa2ba20.png)
![2019-11-08_14 15 38](https://user-images.githubusercontent.com/57531292/68479584-f2011900-0232-11ea-9ab0-6deb10ccd1c3.png)
![2019-11-08_14 15 55](https://user-images.githubusercontent.com/57531292/68479587-f4637300-0232-11ea-98bf-1ff7a3d4eebd.png)
The config settings for the Coal deposit are:
[{
			"blocks": [
				"geolosys:ore_vanilla:0",
				100
			],
			"samples": [
				"geolosys:ore_sample_vanilla:0",
				100
			],
			"yMin": 150,
			"yMax": 200,
			"chance": 8,
			"size": 200,
			"dimBlacklist": [
				-1,
				1
			],
			"density": 0.005,
			"blockStateMatchers": ["minecraft:air"]
		},
And for the Hematite deposit:

{
			"blocks": [
				"geolosys:ore:0",
				100
			],
			"samples": [
				"geolosys:ore_sample:0",
				100
			],
			"yMin": 150,
			"yMax": 200,
			"chance": 6,
			"size": 200,
			"dimBlacklist": [
				-1,
				1
			],
			"density": 0.01,
			"blockStateMatchers": ["minecraft:air"]
		},

If you set the size lower its not that noticable, but still occurs.
Maybay you could backport the "type"-feature from the 1.14 version ?

**Comment by oitsjustjose** [comment]
> Maybay you could backport the "type"-feature from the 1.14 version ?

Definitely not because that took a long time and a lot of work, and not much of it is directly compatible with 1.12, but it's pretty clear to me what's happening!

On pluton generation, if a pluton's ore block is going to be placed outside of its current chunk, it stored it in "`PendingBlocks`" to generate later once that chunk is generating (to prevent cascading lag). It seems that in doing so, I'm managing to ignore the `density` attribute  *on storage* of a `PendingBlock`, but not when I'm within the original chunk.

I'll look into it!

**Comment by barttraeger** [comment]
Thank you!
