### ISSUE TITLE
localization broken in 3.0.9

### ISSUE THREAD

**Issue by dadobug1111** [oitsjustjose/Geolosys#222]
# Versions

Forge Version:
1.12.2-forge-14.23.5.2838
Mod Version:
3.0.9
# Other Mods

none

# latest log
[latest.log](https://github.com/oitsjustjose/Geolosys/files/3833127/latest.log)

# info
![2019-11-11_13 44 10](https://user-images.githubusercontent.com/33583954/68618720-954e6a00-048f-11ea-91cc-41f0525fb20b.png)

this does not happen on 3.0.8 or older

**Comment by oitsjustjose** [comment]
What language are you on? I'm on the latest version as well (in my singleplayer pack) and having no issues:

![](https://i.imgur.com/oL9L0dB.png)

**Comment by RiverC** [comment]
Thanks. I noticed this too. Has config changed?

**Comment by oitsjustjose** [comment]
So, TL;DR is that either my occasional use of Windows, or an issue with Git/GitHub, has caused the capitalization of locale files to be botched.

I think this is why the last update (3.0.9) went out without me noticing, is that on *Windows* it wasn't happening to me.

I'm testing stuff now, but I'm pretty sure it's fixed by 584573d6955e78137a9f27391b491573f153969b

**Comment by oitsjustjose** [comment]
Alright, on my mac this is confirmed working so I'm going to call this closed. 

macOS and Linux / Unix-based Operating Systems *are* case-sensitive, and Windows is not -- so I think it's safe to say that if it's working on a case-sensitive OS, it should work on a non-case-sensitive OS as well :smile:

**Comment by RiverC** [comment]
Yes, this problem has killed whole Magento installations. A good case for running things in a vagrant..
