### ISSUE TITLE
Crash (with no crash log) when opening the book

### ISSUE THREAD

**Issue by Insane96** [oitsjustjose/Geolosys#233]
# Versions

Forge Version: 28.2.1

Mod Version: 4.0.11

# Other Mods

AutoRegLib-1.4-35.jar
corail_woodcutter-1.1.1-1.14.4.jar
Geolosys-1.14.4-4.0.11.jar
ProgressiveBosses-2.1.4.jar
The-Endergetic-Expansion-1.14.4-v1.1.2.jar
bambooblocks-1.2.12.jar
'DefaultAmplified(1.14.4)-1.4.0.jar'
jmh_1.14.4-2.2.jar
Quark-r2.0-210.jar
traverse-1.14.4-2.0.3.jar
BetterCaves-1.14.4-1.1.1.jar
dimdungeons-1.03-forge-1.14.4.jar
KleeSlabs_1.14.4-7.4.8.jar
ReAuth-1.14-3.8.0.jar
TropicalV1.0.0.jar
bloomful-1.2.4.jar
Dirt2Path-1.0.0.jar
modnametooltip_1.14.3-1.12.1.jar
rys-0.1.18.jar
underwaterench_1.14-1.0.jar
Blur-1.1.0-1.jar
FastFurnace-1.14.4-2.2.4.jar
MouseTweaks-2.13-mc1.14.4.jar
SaveMyStronghold-1.14.4-1.0.0.jar
Upgrade-Aquatic-1.14.4-v1.4.10.jar
Charm-1.14.4-1.5.1.jar
FastLeafDecay-v17.jar
mysticallib-1.14.4-1.14.0.jar
swampexpansion-1.3.jar
cndtpd_1.14-1.0.jar
FastWorkbench-1.14.4-2.1.4.jar
Placebo-1.14.4-2.3.5.jar
swingthroughgrass-1.14.4-1.3.2.jar

--

# Logs (if applicable): 
https://pastebin.com/raw/H5eaSNwS

The game just suddently close as soon as I press the right mouse button

**Comment by oitsjustjose** [comment]
It's Blur, I had this same issue myself. I'm not sure what the cause is since there isn't a crash report, but here's how to fix it:

In `blur-client.toml`, find the line that says `guiExclusions = ["net.minecraft.client.gui.screen.ChatScreen"]` and add `"com.oitsjustjose.geolosys.client.manual.ManualScreen"`, so that it looks like:

`guiExclusions = ["net.minecraft.client.gui.screen.ChatScreen", "com.oitsjustjose.geolosys.client.manual.ManualScreen"]`

**Comment by oitsjustjose** [comment]
To be honest it may be something to do with my implementation of the manual GUI, so I'll ask TTerrag if they know.

**Comment by Insane96** [comment]
Wow thanks for the fast response.
