### ISSUE TITLE
Disable Vanilla ore Gen 1.16.4

### ISSUE THREAD

**Issue by LokyLive** [oitsjustjose/Geolosys#253]
# Versions

Minecraft: 1.16.4
Forge Version: 35.1.32

Mod Version: 5.0.0

# Other Mods : none

When Vanilla worlgen is disabled , minecraft:emerald_ore and minecraft:infested_stone still spawn in mountain underground.

PS: Could you add an option in cfg file to disable mod example worldgen generation  ?

**Comment by oitsjustjose** [comment]
I've found this same issue in my testing world and am trying to come up with a solution to this as well.

As for your PS, I don't think I will be doing this just because it could add some unexpected behavior if someone turns it on and doesn't realize. The expectation as of now is that you'll need to disable all other mods' ore generation where desired, so I'm unsure how good of an idea it is to change it at this point.
