### ISSUE TITLE
Finding ores and prospecting

### ISSUE THREAD

**Issue by Thyriel** [oitsjustjose/Geolosys#27]
So far i only did a quick test with worldstripper but it seems to me (compared to TFC) a slightly change in how the prospector hammer works and when surface samples are generated (to work more like in TFC) would be more fun.

Currently (as far as i can tell from my testing) it seems to work like this (correct me please if that's wrong):
- every cluster generates like 1-3 samples on the surface, exactly above the cluster
- so all you need to do is find a sample on surface, dig down on it's position and mine the whole cluster.
- hammer seems only to find ores in a 5x5x5 area (so that's 125 blocks, i guess the limit is to reduce lag ?)

So imho that hammer is pretty useless as EVERY cluster generates surface samples. (At least i did not find any with worldstrip that didn't had samples laying on them after stripping)

As far as i remember in TFC it worked slightly different, which i think was a much greater challenge, especially for higher tier ores (= spawning only deeper) and i think this could be achieved again with some minor changes:
- spawn surface samples only when clusters are no more then 32 blocks (configurable would be great) under the surface (so you need to prospect for ores that only spawn deeper). Maybe even spawn them randomly away from the cluster (within like 20-30 blocks or so) so you still need to search for clusters after finding surface samples.
- Change hammer to not prospect an area, instead only prospect a configurable deep exactly under the clicked block. (Not sure what a good default deep would be but 64 or so should do it). This way it could actually be used to search veins without checking insane amounts of blocks. (Maybe even doable to give it a horizontal/vertical switchable mode ? )

edit: Btw do you have any plans to implement TFCs poor/normal/rich vein system or the mineshaft mechanic (collapsing, etc.) ?

**Comment by oitsjustjose** [comment]
I think, based on what you’re suggesting, you’re looking for a TFC / TFC Ore clone. 

That’s not what Geolosys is. 

I don’t plan on adding a quality system to the ore clusters. If you try actually *playing* in survival wit the prospectors pick, you’ll discover it’s actually an invaluable tool that makes deposit collection less tedious. 

I didn’t copy, or even refer to, TFCs code in any way when writing Geolosys, so as a result tons of stuff is different, and intended to be. Samples generate the way they do because I’m keeping to “normal” modded ore heights (i.e. diamond and Redstone and platinum generate low, tin and others slightly higher, bauxite practically on the surface, etc.). If I implemented samples the same way TFC did, you’d literally never stand a chance at finding the resources you actually need in order to progress in your average mod pack. 

I appreciate the input, and these aren’t *bad* ideas, but they aren’t original; they all seek making Geolosys a TFC replacement or a “modern TFC”, which it isn’t.

**Comment by Thyriel** [comment]
You wrote on the wiki that it's inspired by TFC ;)
So if it's not a "modern TFC" you are trying to do with the mod, what is it that geolosys is trying to aim at ?
Cause currently it doesn't seem to be more then yet another vein/cluster ore generation mod (although there's others that have a lot more config options in doing this, e.g. OreTweaker).
Honestly, even replacing the mined ores in your hand against "clusters" isn't changing anything in gameplay as they are still 1:1 useable like vanilla ores.
