### ISSUE TITLE
Global Datapacks and 1.16

### ISSUE THREAD

**Issue by Tellik** [oitsjustjose/Geolosys#291]
## Versions:

- Minecraft Forge: 36.2.23
- Geolosys: 1.16.5-6.0.1_beta

## Additional Comments: Well this is expected behavior since "Starting as of Geolosys's port to Minecraft 1.16, all plutons in Geolosys are now registered using Datapacks! Datapacks are a fantastic, flexible way of adding or modifying content in Geolosys your heart's desires!"

However, this completely makes this mod unusable for 1.16 as there are no working forge 1.16 global data pack mods available. The one suggested has an open (since July) bug report that prevents it from working completely. I wasn't able to find any that would work for this. Meaning the only way to use this mod is by copying a datapack each time a world is created. However, this is a silly process, especially for a mod pack, and isn't feasible.

This is more of an FYI kind of report, just to let you know about this problem. It's a shame because I was wanting to be able to use this mod in a new pack I'm working on. Though even using this in a single player world would get tedious after the first couple times.

**Comment by oitsjustjose** [comment]
Hi there.

I'm not sure what other mods you may be using that would make this be the case, but in my (very recent, like literally Monday I was developing a modpack using the [Global Data & Resource Packs mod](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack)).

There is [this bug](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack/issues/4) that has been open since July, I presume that's the one? Well,

1. That's for *Resource*packs, not datapacks. Even if you're experiencing the same issue for datapacks, then
2. Neither Datapacks nor ResourcePacks need to be zipped. You can unzip them, leave them in the `global_data_packs` or `global_resource_packs` folder, and they will work. Check out [my Modpack](https://github.com/oitsjustjose/Harmonious-Engineering/tree/3acef7947c76f726212ceb0fdbe499fed889c63c) and how I stored resource and datapacks, that should help.

Lastly, both CraftTweaker and KubeJS have support for "Custom Recipes":

## From [the KubeJS docs](https://mods.latvian.dev/books/kubejs/page/recipeeventjs):

```js
  event.custom({
    type: 'create:crushing',
    ingredients: [
      Ingredient.of('minecraft:oak_sapling').toJson()
    ],
    results: [
      Item.of('minecraft:apple').toResultJson(),
      Item.of('minecraft:carrot').withChance(0.5).toResultJson()
    ],
    processingTime: 100
  })
```

## From [the CraftTweaker docs](https://docs.blamejared.com/1.16/en/mods/other_mods)

```zs
<recipetype:charcoal_pit:barrel>.addJSONRecipe("crafttweaker_barrelcustom_1", {
  "item_in":{
  	"item":"minecraft:wheat"
  },
  "fluid_in":{
  	"fluid":"minecraft:water",
  	"amount": 250
  },
  "fluid_out":{
  	"fluid":"charcoal_pit:alcohol_still",
  	"amount": 250,
  	"nbt":"{CustomPotionColor:16624200,Potion:\"charcoal_pit:beer\"}"
  },
  "flags": 1,
  "time": 48000
});
```

Both of these would work and you would just need to change them to match the JSON format to match Geolosys's. 

Sorry you've been facing frustration regarding this topic. Let me know if I can help further.

**Comment by Tellik** [comment]
The issue is, GD&R doesn't generate any required folders or config files to be able to setup a global datapack. Reading through things a little bit more, it seems like it would work if I generated the folder at least myself? I just took how it didn't make the config file that nothing was happening.

This is the issue I was referencing specifically. https://github.com/DarkRoleplay/Global-Data-and-Resourcepacks/issues/5

Reading over things a little more it seems like just generating the folder would solve everything, though I was getting hung up on the mod description saying that I needed or had a config file that wasn't there.

I'm glad that there are a few other options that I can try if I have any other issues, and I'll give them a shot to see how it goes. Everything has changed since I last was working on a pack back in 1.12 and it's really thrown me off. Thank you for your assistance.

Edit: It turns out the config file isn't generated until the folder is created. If I need more assistance (I'll continue giving it a try here but I probably will, should I open a new ticket?)

Edit x2: "Neither Datapacks nor ResourcePacks need to be zipped. You can unzip them, leave them in the global_data_packs or global_resource_packs folder, and they will work. Check out my Modpack and how I stored resource and datapacks, that should help."

It turns out that they do NEED to be zipped. At least for 1.16.5. I spent all night trying various things to get it to work but in the end, as soon as I zipped it, it worked perfectly.
