### ISSUE TITLE
Long world save due to Geolosys

### ISSUE THREAD

**Issue by Sleepwalkerx** [oitsjustjose/Geolosys#307]
## Versions: 
Geolosys 1.16.5 6.0.1_beta

## What happens: 
Generally. I use your mod in one of the worlds for custom ore generation. However, because of this, the world in which this is all generated keeps longer and longer each time. My server has been online for 14 days now and the save times are up to 26 seconds (they happen every 6000 ticks).

## What should happen:
there should not be a save of 26 seconds.

## Additional Comments: 
I ran Spark to find the source of freezes and found that your mod is very heavy on the world. I also use my own ore generation files (I attached them). Freeze sources are definitely in vogue, because without it everything works fine.

![image](https://user-images.githubusercontent.com/62907629/166615491-ce4cad31-6fb6-48da-8682-32e5f209bec7.png)
[ore.zip](https://github.com/oitsjustjose/Geolosys/files/8617599/ore.zip)

**Comment by hydroj** [comment]
Can confirm this issue also occurs on my server running Geolosys 7.0.5 (1.18.2). Deleting the geolosys:deposits branch in capabilities.dat using a NBT editor seems to temporarily fix this, but I'm not sure if this breaks anything.

**Comment by oitsjustjose** [comment]
Fixed in e8d53511fd7429ea2d9f634567f9ea6e2d25dec4 - in local testing my previous implementation would cause the creation of about 12000 entries in total. After this fix the number hovers around 64-128 and never fluctuated above 512 or so. This will never reach 0 because of how the world is infinite, but this is a significant improvement.
