### ISSUE TITLE
[Suggestion] Multiple clusters per ore (And fortune)

### ISSUE THREAD

**Issue by Jomik** [oitsjustjose/Geolosys#37]
I think it'd be nice if the ores could drop multiple clusters, depending on various factors, like closeness to center of pluton or something like that.
Especially because it seems to be quite a bit harder to get ores, so you should be set for quite a while when you do find them.
I also think it'd be nice to then support fortune on the ores.

**Comment by oitsjustjose** [comment]
See other response.

**Comment by darthvader45** [comment]
Mind linking the "other response" if it still exists?  I assume the reason is since there are so many blocks per deposit, the fortune enchant becomes redundant?

Edit:  Seems it is because it isn't necessary unless some modpack makes a certain ore or item extremely, ludicrously rare.  Though maybe adding a config option might be cool, defaulted to off.  That way, modpack makers can turn it on if they need it, or keep it off if not.

**Comment by Jomik** [comment]
I believe the answer was that it is out of scope of this mod.
