### ISSUE TITLE
[suggestion] machine to help find surface samples

### ISSUE THREAD

**Issue by Zygus42** [oitsjustjose/Geolosys#6]
Some way to direct a player towards surface samples, either something as simple as a Dowsing rod, or perhaps a machine you have to set up, feed with resources and wait for a result to get an approximate direction to the nearest sample.  Should not be too simple or easy, but with heavily modded terrain such as BoP, surface samples can be almost impossible to find by eye.

**Comment by oitsjustjose** [comment]
I don't care for this idea, but I can see how it could be absolutely necessary to do because of the complexity of some surfaces (thinking of how hard it'd be to find one in a Botania world, when that updates). 

What if I did this: a new config option that allows samples to spawn on a stone structure. It'd look something like this:

![2017-07-19_10 08 45](https://user-images.githubusercontent.com/3887324/28371198-4d505e76-6c6a-11e7-8c5b-b9f187eb989b.png)

Thoughts? This'd be certainly much easier to see. Maybe even incorporate some of the actual ore down under into those stones, like this:

![2017-07-19_10 09 50](https://user-images.githubusercontent.com/3887324/28371237-68b62ee8-6c6a-11e7-9297-7679fbc2b967.png)

**Comment by Zygus42** [comment]
That could be okay - would need to try and find it in a BoP world and see.  I can see you want it to kind of look like a real life ore vein, but how about if the blocks were granite or diorite or something like that that look very different from normal terrain.  

Another alternative would be to spawn a 5 or 6 samples in the chunk instead of just 1 - I find them fairly easy to find, but just 1 gets lost easily.

**Comment by oitsjustjose** [comment]
Either one of those two is totally do-able. I like the idea of multiple ones - it might help with inconsistent generation of samples too.
