### ISSUE TITLE
[Suggestion] IE Deposit Compatibility

### ISSUE THREAD

**Issue by Yankas** [oitsjustjose/Geolosys#64]
I think a nice optional feature would be to add optional integration with Immersive Engineering Mineral Deposits. It would make for nice synergistic gameplay, in the early game you can mine the deposits generated by this mod, and later on you can extract whatever is "left" with an excavator. The way it would work is like this:

If Immersive Engineering is loaded, and the feature is enabled, every time this mod spawns one of its own large, it would also make sure to force the related chunk(s) to have a corresponding IE mineral deposit.

**Comment by oitsjustjose** [comment]
This is an absolutely awesome idea. I'll look into the IE API and see if it's possible for me to integrate!

**Comment by oitsjustjose** [comment]
Can you give [this beta](http://www.mediafire.com/file/4vzkkbzcvyjmeen/Geolosys-1.12.2-1.8.6-INDEV.jar) a try and let me know if the implementation needs any changes?

Anything at all, such as rarity, failure chances, the item resulting from the excavation, etc.

Thanks!

**Comment by Yankas** [comment]
The first thing I noticed is that the Excavator outputs the "Ore Block" instead of the metal "cluster", I am guessing this is not intended behavior. So that should probably be fixed.       

As for changes,  since this is still a Work in Progress that was released very quickly (!), I am guessing that some of these features are already being planned/implemented so ignore redundant suggestions:       
- I still think it would be nice to link the IE Deposits to your own, though after a quick glance at IE's ExcavatorHandler it looks like overriding functionality is exposed and might require some reflection magic.     
-  If you want to keep the current way of keeping IE's distribution and just replacing the deposit/output types, then I'd suggest adjusting the spawn chances (currently hardcoded) to match the xxxChance values in the geolosys_ores.jon.

**Comment by oitsjustjose** [comment]
I actually did intend this behavior, and thought that it was more fitting to the style of the excavator if it returned the ore *block* itself instead of the cluster. I'll poll twitter and see what they think.

As for your bullets:

1. I already did this, no reflection required. I manually remove all the excavator's existing entries if the compat is enabled, and then add my own afterwards.

2. Also already doing this; I'm initializing the MaterialMix with the JSON's chance values :)

**Comment by MooTorial** [comment]
Not to revive a dead post, but did anything ever come of that twitter post? Excavators still draw up just the blocks. They're no recipes to automate their processing.

**Comment by oitsjustjose** [comment]
[This](https://twitter.com/oitsjustjose/status/965246214181670913) reminded me what the problem was to begin with; turns out if I did clusters (preferred) it graphically looks bad. I haven't seen any updates to the API I'm using to allow me to change it so that it visually extracts ore blocks, but what goes in the chest is a cluster item.

**Comment by MooTorial** [comment]
That's definitely an interesting insight. Do you have any recommendations
for a block breaker mod then? I'm sure there's many out there.
,
