### ISSUE TITLE
(Suggestion) Chalcocite or chalcopyrite as higher yield copper ore

### ISSUE THREAD

**Issue by WrongWeekend** [oitsjustjose/Geolosys#70]
Azurite is potentially a usable ore of copper but not a particularly good source of it due to its rarity in real life. Chalcopyrite and chalcocite on the other hand are much more abundant and important sources of copper. The former is also an iron source, and both can be processed for sulfur.

**Comment by oitsjustjose** [comment]
*Maybe*.

I don't disagree in the slightest, but I have a few personal quarrels with it that have nothing to do with the logic behind it.

1. I like azurite's appearance a *lot*, both IRL and the texture 😛 
2. Worlds have already generated with Azurite, so it'd have to be *replaced* with Chalcocite completely (ie: same block and metadata) leaving no Azurite behind (see [1] as to why I dislike this)
3. I don't have a texture artist anymore due to personal saving necessities, so I don't know that I'd be able to *get* a nice new texture for chalco[cite/pyrite]. If you haven't seen the new coal variant textures, then you aren't aware how bad this actually is o_o


I'm leaving this open. Maybe one day I can afford to have @wiiv around again - I loved his textures.

**Comment by WrongWeekend** [comment]
I wouldn't mind creating some textures for the ores myself, and perhaps others like wolframite for tungsten.

On an unrelated note have you considered setting up a discord server?

**Comment by oitsjustjose** [comment]
Honestly, I'm pretty happy with how things are now and if I changed it *now*, all the users of SevTech would be quite confused. 

Thanks for the offer and suggestion though!!
