### ISSUE TITLE
Immersive Engineering and Geolosys

### ISSUE THREAD

**Issue by bookerthegeek** [oitsjustjose/Geolosys#72]
## Heyo! ##
Hello good sir! Love your mod (It is just what I am looking for) and the fact that you integrate with IE mineral deposits. Just a couple of quick question though....

According to the configs (snippet below) and my testing, this should make it so that Yellorium and Platinum are not drops. Which after breaking an inordinate amount of ores in my test setup (Creative item provider and block placers/breakers) seems to be the case
```
"Feature Control" {
    B:"Replace Stone Variant Deposits"=false
    B:"Enable Yellorium"=false
    B:"Enable Osmium"=true
    B:"Enable Osmium Exclusively (without platinum)"=true
```
Now, the issue is that the engineering manual from IE which you modify, shows that Platinum is a 50% rate from the "Platinum mineral vein", and that Yellorium is a 50% drop from the "Autunite mineral vein". Is there any way to have that reflect the configs?

### Other questions ###

- Can we get separate silver and lead ore blocks in addition to the Galena?
- A way to configure the drop percentages when a block has more than one output, for example the assorted quarts?
- Is there a hardcoded limit to how big I can make the veins? Or a max number you would suggest not going over?
- In the `geolosys_ores.json` it shows a chance to spawn, for example `"goldChance": 3`. Can you explain how that works please.
- Would it be possible to include an option to turn off vanilla world generation of overworld ores? That would stop people from having to install another mod to disable that.
- Any way to include functionality similar to the following mods? I completely understand if that is outside the scope of this mod though.
  - [UBC Ore Registrar](https://minecraft.curseforge.com/projects/ubc-ore-registrar) 
  - [Ore Stone Variants](https://minecraft.curseforge.com/projects/ore-stone-variants)
- When Platinum is turned off in the configs, can the Ore name be changed to Osmium, or would it just be easier to use Minetweaker?
- Same as above but for the [IE mineral Vein](https://github.com/oitsjustjose/Geolosys/blob/0a2f0229987c1b30281ddaa2bd6a56b44d75e426/src/main/java/com/oitsjustjose/geolosys/compat/ie/IECompat.java#L132).
- In [IECompat.java](https://github.com/oitsjustjose/Geolosys/blob/0a2f0229987c1b30281ddaa2bd6a56b44d75e426/src/main/java/com/oitsjustjose/geolosys/compat/ie/IECompat.java#L120) on line 120 you specify that Lapis dust will drop. Seems odd is all. Any way to suggest that that be changed to actual Lapis? If not I can Modtweaker it to drop Lapis instead. Just my 2 cents.

### Finally ###
Thanks for your hard work, and this amazing mod by the way.

**Comment by oitsjustjose** [comment]
Phew.. thanks for this super extensive (and well formatted and detailed) list of suggestions!

I'll go down one-by-one so that it's easiest to read:


### Regarding IE Osmium and Yellorium compat

Totally an oversight on my part. A fix has been implemented. I seriously can't believe I didn't think about it >_<

### Separate silver and lead

That's... pretty unlikely. I no longer have a texture artist (which is a bad thing if you want new features), which was a decision I made because I need to save up money to move *plus* I'm pretty happy with where Geolosys is right now. You could add custom entries if you find yourself needing more.

### Multi-drop percentages

I'll _consider_ this, but I honestly don't know that this will ever be necessary unless you have a customized pack that is ludicrous on something like, say, Certus Quartz. I've played with Geolosys extensively with *all* of the mods that I add compatibility drops for, and have never once been short on 
anything I had gone mining a *lot* for.

### Chances

So, the chance is just that. The higher the chance, the more likely you are to find it. Behind the scenes, I go through and store the largest chance you have set as a variable. When the `generate` method is called, I start a loop where I pick a random ore from the list of ores that can generate, and a pick a random number between 1 and the biggest chance available. If the randomly selected ore's chance is greater than or equal to the random number between 1 and the largest chance, then that ore is selected to generate.

So, in turn, a higher chance prioritizes that ore *more*, but doesn't exclude the other ones in any way.

### Vanilla World Gen

Such as disabling vanilla Iron ore or Redstone ore? It's already been a thing since the very first release of Geolosys, it's done automatically if the chance of any entry in the `geolosys_ores.json` file is greater than 0. So, if you have Limonite and Hematite disabled, then vanilla Iron *won't* be disabled.

### Ore -> Stone Variants

I've *actually* kinda been thinking about this... I will get back to this at some point; the execution wouldn't be hard at all, but it would be a pain to make all these new textures. Plus, I'm a perfectionist, so I'd end up having to change the Texture system a lot to work like Tinkers' Construct's Ardite and Cobalt. TiCon uses whatever netherrack texture *you're* currently using, and then overlays the ore texture on *top* of it for a seamless experience. If I did that many stone variants, I'd want it to be just as seamless. 

### Platinum naming

Probably a Minetweaker thing honestly, names are controlled in geolosys via the `en_US.lang` file.

### Platinum naming in IE

I'll fix this myself, actually. Super easy.

### `IECompat` Lapis drop

`dustLapis` is just the OreDictionary name for normal Lapis Lazuli, so nothing for you to worry about here.

**Comment by bookerthegeek** [comment]
Thanks for the quick fix, and the detailed response. I knew there was a reason I liked this mod. ;) Keep up the good work my friend.

**Comment by bookerthegeek** [comment]
I hate to Nitpick.... But in [IECompat.java](https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/compat/ie/IECompat.java#L118), on line 118, you have
```
ExcavatorHandler.addMineral("Lapis", Geolosys.getInstance().configOres.lapisChance, 0.05F, new String[]{"dustLapis"}, new float[]{1.0F});
```
Which is giving Lapis Dust. Lapis is OreDictionary to `gemLapis`. Any chance of changing it?

---
![Lapis Lazuli](https://i.imgur.com/gsDa5hN.png)
![Crushed Lapis](https://i.imgur.com/XfbwWzg.png)

**Comment by oitsjustjose** [comment]
You know when you look for something and you swear you can't find it, but then someone else looks for you and finds it in 2 seconds?

Something like that kinda happened.

I looked at the OreDictionary class offered by forge and ***swore*** that Lapis was registered as a dust. **SWORE**.

Nope.

So, yes, this has been for-real fixed. Sorry :|
