### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by DevTimur** [oitsjustjose/Geolosys#84]
1) Add Certus quartz into Quartz ore drop (AE2 quartz)
2) Add Ritule ore (Titanium)
3) Prospectors pick should have durability, and be cheaper to make.

**Comment by oitsjustjose** [comment]
1. It already does this. And Charged Certus. And Black Quartz from actually additions
2. This has been requested before but was denied. You can use the config file to create your own veins of rutile though!

**Comment by DevTimur** [comment]
How can i add own surface sample?
You need a better tutorial then this:

"User Entries" {
    # Format is:
    # modid:block:meta, clusterSize, min Y, max Y, chance to gen in chunk. Example:
    # actuallyadditions:block_misc:3, 32, 13, 42, 20
    # Optionally you can declare your own "sample" block by appending an extra modid:block:meta to the end. Example:
    # actuallyadditions:block_misc:3, 32, 13, 42, 20, actuallyadditions:block_misc:1
    # META, COLONS AND COMMAS ARE REQUIRED.
    S:"Custom Ore Entries" <
	minecraft:clay:0, 32, 13, 42, 20, minecraft:clay:0
     >

**Comment by oitsjustjose** [comment]
I don't think I need a better tutorial.. what you've posted already does exactly what you want! If you want something that *looks* like a Geolosys sample on the surface (instead of just clay blocks), you'll need to use some other mod like ContentTweaker.

SevTech:Ages does this. Here's an example where ContentTweaker was used to create a custom sample for GalacticCraft's Silicon Ore:

`galacticraftcore:basic_block_core:8, 24, 24, 48, 12, contenttweaker:sub_block_holder_0:5`
